import type { AppProps } from "next/app"
import "./../styles/style.scss"
import Head from "next/head"
import { store } from "@/store/ReduxStore"
import { Provider } from "react-redux"

export default function App({ Component, pageProps }: AppProps) {
  return <div className="MainWrapper">
    <Head>
      <title>Good deeds</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Provider store={store}>
      <Component {...pageProps} />
    </Provider>
  </div>
}
